apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - ./longhorn.yaml
  # - https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
