---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv-volume
#   labels:
#     type: local
#     app: postgres
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv-manual
#   labels:
#     storageclass.storage.k8s.io: local-storage
# spec:
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /data/postgres
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - d1
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: postgres-pv-claim
#   labels:
#     app: postgres
# spec:
#   storageClassName: local-path
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
  # selector: 
  #   matchLabels:
  #     app: postgres
  #     hostname: d1
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pv-claim
#   namespace: default
#   labels:
#     app: postgres
#     env: dev
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  annotations:
    k3s.io/hostname: kube4
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-simple-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      nodeSelector:
        db: dev

      volumes:
        - name: postgredb
          # persistentVolumeClaim:
          #   claimName: postgres-pv-claim
          hostPath:
            path: /data/postgres
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---


