apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: dev

# bases:
#   - ../base/postgres-simple

resources:
  - ./namespaces.yaml
  - ../base/postgres-simple
  - ../base/keycloak
  # - ./application-argo-workflow.yaml
  # - ./application-postgres-dev.yaml

# patches: 
# - patch-argocd-repo-server.yaml

configMapGenerator:
- name: keycloak-env
  behavior: merge
  literals: 
  # - DB_ADDR="postgres"
  - POSTGRES_HOST="postgres"
  # - POSTGRES_ADDR="postgres"
  - POSTGRES_DATABASE="postgres"


# generators:
#   - ./secret-generator.yaml

