apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: argo

# bases:
#   - ../../../base/fluent-bit
bases:
  - ../minio

# Latest argocd 
  # curl -sLO https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
  # curl -sLO https://raw.githubusercontent.com/argoproj/argo/v2.8.1/manifests/install.yaml

resources:
  - ./install-2.8.1.yaml
  - ./rbac.yaml

patchesStrategicMerge:
  - ./workflow-controller-configmap.yaml


# generators:
# - ./secret-generator.yaml

# add runtime executor as Process Namespace, help:  https://argoproj.github.io/docs/argo/workflow-executors.html
# configMapGenerator:
#   - name: workflow-controller-configmap
#     literals: 
#       - containerRuntimeExecutor=pns
#     behavior: merge