apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cr
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - pods/exec
  - secrets
  - ingresses
  - services
  - jobs
  - deployments
  - statefulsets
  - cronjobs
  - workflows
  - configmaps
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo
  name: builder
