apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
stringData:
  accesskey: minio # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: TLoLSJ6EHr0nm8Xc # based 64 encoded "minio123" (echo -n 'minio123' | base64)