apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  # namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik/traefik
    repoURL: https://containous.github.io/traefik-helm-chart
    # helm:
      # valueFiles:
      # - values.yaml
    # targetRevision: 7.6.1
