apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      selfHeal: true
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: traefik
    repoURL: https://github.com/containous/traefik-helm-chart
    targetRevision: HEAD
    helm:
      values: |
        image:
          name: traefik
          tag: 2.1.8
        additionalArguments:
          - --log.level=DEBUG
          - --accesslog=true
          - --metrics.prometheus=true
          - --metrics.prometheus.addEntryPointsLabels=true
          - --metrics.prometheus.addServicesLabels=true
          - --global.sendAnonymousUsage=false

