apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      selfHeal: true
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: minio
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 5.0.26
    helm:
      values: |
        service.type=LoadBalancer
        fullnameOverride=argo-artifacts