apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: traefik
    repoURL: https://github.com/containous/traefik-helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
    # targetRevision: 2.2.1
