apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-cluster-common
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: cluster
    server: https://kubernetes.default.svc
  project: default
  source:
    path: commons
    repoURL: git@eu-de.git.cloud.ibm.com:raseedyops/cluster-applications.git 
    targetRevision: HEAD
  syncPolicy:
    automated: {}
