apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: 
      selfHeal: true
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stable/minio
    repoURL: https://github.com/helm/charts/tree/master
    targetRevision: HEAD
    helm:
      values: |
        service.type=LoadBalancer
        fullnameOverride=argo-artifacts