apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v0.15.1
    helm:
      parameters:
      - name: installCRDs
        value: "true"

