apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: argocd

bases:
  - ./cert-manager
#   - ../../../base/fluent-bit


resources:
  - ./namespaces.yaml
  - ./application-traefik.yaml
  - ./application-elasticsearch.yaml
  - ./application-cert-manager.yaml
  # - ../base/longhorn
  - ./application-longhorn.yaml  
  # - ./application-common.yaml  

  # - ./cluster-ibm-dev.yaml

# patches: 
# - patch-argocd-repo-server.yaml



# generators:
#   - ./secret-generator.yaml

