apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: argocd

# bases:
  # - ./cert-manager
#   - ../../../base/fluent-bit


resources:
  - ./namespaces.yaml
  # - ../base/nginxlb
  - ./application-traefik-lb.yaml
  # - ./application-traefik.yaml
  # - ./application-kong-kustomize.yaml
  # - ./application-elasticsearch.yaml
  - ./application-cert-manager.yaml
  - ./application-common.yaml  
  # - ./application-bootstrap-ibm-dev.yaml
  - ./application-argo-workflow.yaml
  - ./application-minio.yaml

