apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: cluster

bases:
  - ../../../base/fluent-bit


resources:
  - ./application-traefik.yaml

# patches: 
# - patch-argocd-repo-server.yaml



# generators:
#   - ./secret-generator.yaml

