apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kong
  name: ingress-kong
spec:
  template:
    spec:
      serviceAccountName: kong-serviceaccount
      containers:
      - name: proxy
        env:
          - name: KONG_PROXY_LISTEN
            value: 0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 proxy_protocol ssl http2