apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

# main source file
# bases:
#   - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/baremetal/deploy.yaml

resources:
  - ./crd.yaml
  - ./namespace.yaml
  - ./helm/traefik/templates/rbac/clusterrolebinding.yaml  
  - ./helm/traefik/templates/rbac/clusterrole.yaml  
  - ./helm/traefik/templates/rbac/serviceaccount.yaml
  # - ./helm/traefik/templates/service.yaml
  - ./traefik-2.2-daemonset.yaml
  - ./ingress-dashboard.yaml



