apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mw-raseedy-mw-prod
  # namespace: traefik
spec:
  secretName: mw-tls-prod
  issuerRef:
    # The issuer created previously
    name: acmedns-issuer-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.mw.raseedy.io"