apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mw-raseedy-stg
  # namespace: traefik
spec:
  secretName: mw-tls-stg
  issuerRef:
    # The issuer created previously
    name: acmedns-issuer-stg
    kind: ClusterIssuer
  dnsNames:
  - "*.mw.raseedy.io"