---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: acmedns-issuer
spec:
  acme:
    email: shussein@raseedyapp.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: acmedns-issuer-account-key
    solvers:
    - dns01:
        acmedns:
          host: https://auth.acme-dns.io
          accountSecretRef:
            name: acme-dns
            key: acmedns.json