apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: cert-manager

# bases:
#   - ../../../base/fluent-bit

resources:
  - ./issuer-letsencrypt-acmedns.yaml
  - ./certificate-raseedy-stg.yaml
  # - ./certificate-raseedy-prod.yaml

generators:
- ./secret-generator.yaml

