apiVersion: v1
kind: Secret
metadata:
    name: acme-dns
type: Opaque
stringData:
    acmedns.json: ENC[AES256_GCM,data:rOPE3ktnfH9Eoklyfzyc0qYHuvqumzw1HYwFpBog8kcsZeNkeSLxIo9W5bXQQpfjgJz5a2VRc9G1lyIx8VbSI98j976luYZYIkDedPHUbrSeuP1r/4SPvalXoH0E6UM7Vo3fHoptD6QMzTn5yHNjzx7IcNalBjWjCVQppJghjQwYgasShvlUXMpgqBJZ7BPSQFo1zEgSTczTI3NQTKs3Nb2DeMWwEgZ9QKPi+upqPxwuCA5jelI6Xyg2bFKEr3NH0WTpupWwp2EuMjLMep24KrQHgUlqOCwtsz1x3Mj4WkgpUroTXphGrod/oS5NuiY8LUA6oSl6GU4CFDGjwbaKjuz4MiSZQi9n8mttvuKVQgEngTaRMNV5dk120PjlLljxLTUckTM=,iv:jFm467V5BQbxuaYNj88iFA5RWyP9DMX0VUyxXtfFyRg=,tag:vCQTcApC1GQjDDQqil5ZZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://raseedy-gitops.vault.azure.net
        name: sops-key
        version: 24463ded09434256b46852a5cd1a6edf
        created_at: '2020-05-31T22:58:31Z'
        enc: gycFJknicWY47NQojVcM1O1q0Ru2T9P19wAqpG1eGnF8PurxLj8vK8TlaRu3DTiqyqymyZdGEE5QEVK9Trbe4b_YzX8ygXWYsv4FGr8mS2Db8rImG6a47N3xNEOUuEDaLS3hBGXQcIZLfPB-5HW8q5PmTyz-_D-275LuztiaU9N4z9kFsQA0RiiFvMJulI_sEhUdYu6vtlbxjUTkviu9TBjjpwRPj1VereFKRTPxPh2xIvg_grXWJXKU_HQaGyI81rwceYFjEvZPGQUeUy2d5hAO5Noka27w7p7aBWMdYwYyI8yqa58xV2aQB_rWWT7oc1e1Qx0eVDCOQ4h1gKOxpQ
    lastmodified: '2020-06-03T23:25:01Z'
    mac: ENC[AES256_GCM,data:qeoRGrGSzme6Bo6O496+36HZxOgbRXHNIc2J2FERonj7mItPMPNmVwCJwvlFVr5PGyLscFWqxVFr4WoDsqyTh0GTLvsQmkI9/VH4Ueaayjx1ieQ7u1XlhikfKyh4JRPKmS2PSDQp2XoFr7FuBqhOg6EuotMGM2F9N5eOPaeaoGU=,iv:RKzF03lfxRRXxHIE6UlDkX7QfgIRN9zToW7gby9eRes=,tag:bH0zdZkVVSSvJjZJRt1BQw==,type:str]
    pgp:
    -   created_at: '2020-05-31T22:58:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9rJtJUODAqKAQgAnDxNshG7NOOsLsbEpT1N1+2jndmovK1w/g9iGAL8Mjdt
            EAtrBscONyf+6VoK35K4XXGmivxLh6ebS63hdFfPPIoSg4Y+updBF0DTx0qy7cqc
            M2ZcpP1FJ1plMb+z7NHsV9EpJm4+Oz5AHJYDIvPsmF/0+xQ+Rj3uqKcOpamlP0h5
            Jn1BJVXpWfak/LcMQjGrqCqsBfaC7Zl+nrW4qcIxXg9ajP4a2WhqwhxyO/Ffeyuw
            WlSP4XUbIiFlxmC4ehTKxqKaH3Ac3LMXJgrjZSjp2S16xfrBMr79ZIeb13XPHSob
            cbOMl5hSEuUzA+csS7JhX+rwjYM6RrCpxCPaokFN69JcARZqH5V/0c7WYyB+YINI
            0LLE5VWitIGl1tHvEXx5Ec2scFHF+rNokFZidwICyddLQAX48kesdxOC7lPO8z+N
            HuhLvpt0nS+ebOGRdTeNanTdvW4AFtBswUuDC8Y=
            =sINj
            -----END PGP MESSAGE-----
        fp: 8CC3DBB98A442086023F9766A5296C151AD0CA9E
    -   created_at: '2020-05-31T22:58:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA79ZFHB1EZo1AQgAvcmUd6+zwgowc9kesJ0Ky3ANW7Q7oQcoMw8uDiAMcxC9
            hPWq2N4/J9tgfp+2HsInHdVu9pYwbtsigMEjlmBpHFyfIr9zH7AGx1IDD4MMeHAZ
            hJqzeCD8PqZNzyXqGQAlxH9sJG3R8LFQF+VU04N9gAIoZBbmc6h8RMx1XcmbzuFg
            We9IYcKLoRE0EXfnWAFi/VlRrCD2jGKmIUhYzEB+35392U1+2qM6TPm35y6KCwvs
            VTx+XZHuBkbdWe7HWTeBB6mmRx5uZbnCybACJmnHTv5toBgFG5HXTGpJINHtaAMz
            AB2fuX7hC+6YY9tTOrzTUWbqHUJvx6JJ7rTHBJhEntJcAZeVFddWXypoe2Fn6pTF
            VLGoEJanmqG5JYnAEDYjbXOv1q7eBnIqjisaHsYosWWOBbxX+0/q0+JPPFu0fIyX
            5DQ1WG1VG8FlYBzur8ItD5m2d2iKWggmZnUCd8c=
            =fES1
            -----END PGP MESSAGE-----
        fp: 4C70A838416441A4E5A476B46E17861CCB27B2FB
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
