apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: dev
  annotations:
    # kubernetes.io/ingress.class: "kong"
    # kong.ingress.kubernetes.io/force-ssl-redirect: "true"
    # plugins.konghq.com: keycloak-ingress
    # configuration.konghq.com: "kong-configuration"
spec:
  rules:
  - host: kk.dev.raseedy.io
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: http
  tls:
  - secretName: raseedy-tls-stg
    hosts:
      - "kk.dev.raseedy.io"
      - "raseedy.io"
      - "*.raseedy.io"
