apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: kong
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: ab.dev.raseedy.io
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: https
  # tls:
  # - secretName: raseedy-tls
  #   hosts:
  #     - "*.raseedy.io"
  #     - "raseedy.io"
