apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  labels:
    app: keycloak
data:
  POSTGRES_HOST: "postgres.default"
  # POSTGRES_ADDR: "postgres.default"
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: "public"
  POSTGRES_DATABASE: "postgres"
  PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_USER: "keycloak"
  KEYCLOAK_MGMT_USER: "keycloak"
  KEYCLOAK_OWNERS_COUNT: "2"
  DB_VENDOR: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: /nLNZKDC7oEvzDjJYwg8bDiASnNcS20w94d9NLRm6no=
  # POSTGRES_PASSWORD: keycloak
  DB_USER: admin
  # DB_PASSWORD: keycloak
  # # DB_PASSWORD: /nLNZKDC7oEvzDjJYwg8bDiASnNcS20w94d9NLRm6no=
  # # BASE_SCRIPT_DIR: "/scripts"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name:  keycloak
# data:
#   KEYCLOAK_PASSWORD: L2ZNQ0U3Um5JKzFkd3o3cGF4Sko1bW54bUlPMGFtemZOSzRubklmdTZpRT0=
#   KEYCLOAK_MGMT_PASSWORD: L2ZNQ0U3Um5JKzFkd3o3cGF4Sko1bW54bUlPMGFtemZOSzRubklmdTZpRT0=
# type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  keycloak
  namespace: default
  labels: 
    name:  keycloak
    app: keycloak
    env: dev
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app:  keycloak
    spec:
      containers:
        - name:  keycloak
          image:  jboss/keycloak
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: keycloak-env
            # - configMapRef:
            #     name: postgres-config
            - secretRef:
                name: keycloak-secret
            - secretRef:
                name: postgres-simple-secret
          # env:
          #   - name:  POSTGRES_PASSWORD
          #     valueFrom:
          #       # secretKeyRef:
          #       configMapRef:
          #         name: postgres-config
          #         key:  POSTGRES_PASSWORD
          ports:
            - name: https
              containerPort: 8443
            - name: management
              containerPort: 9090
            - name: jgroups-tcp
              containerPort: 7600
            - name: jgroups-tcp-fd
              containerPort: 57600
            - name: jgroups-udp
              containerPort: 55200
              protocol: UDP
            - name: jgroups-udp-mc
              containerPort: 45688
              protocol: UDP
            - name: jgroups-udp-fd
              containerPort: 54200
              protocol: UDP
            - name: modcluster
              containerPort: 23364
            - name: modcluster-udp
              containerPort: 23364
              protocol: UDP
            - name: txn-recovery-ev
              containerPort: 4712
            - name: txn-status-mgr
              containerPort: 4713
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-external
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: https
      port: 8443
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  clusterIP: None
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8443
    - name: management
      port: 9090
    - name: jgroups-tcp
      port: 7600
    - name: jgroups-tcp-fd
      port: 57600
    - name: jgroups-udp
      port: 55200
      protocol: UDP
    - name: jgroups-udp-mc
      port: 45688
      protocol: UDP
    - name: jgroups-udp-fd
      port: 54200
      protocol: UDP
    - name: modcluster
      port: 23364
    - name: modcluster-udp
      port: 23364
      protocol: UDP
    - name: txn-recovery-ev
      port: 4712
    - name: txn-status-mgr
      port: 4713
  type: ClusterIP
