apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
type: Opaque
stringData:
    KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:D7WGlDL4AVeNChA=,iv:DJcO2AWK5puc2FrVry4HEFPoCzAQEYOiE8yj5KrZwKk=,tag:7pQcZsJtIW0OcdLZPuOVVA==,type:str]
    KEYCLOAK_MGMT_PASSWORD: ENC[AES256_GCM,data:Qp6BbWxPqqHh/N4=,iv:5DKJeLJXn4mJyR8+5Lv1CfO0o6puJigz7yllkMLpNpk=,tag:R7rkd1oR7UxGRQSPnt5JCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://raseedy-gitops.vault.azure.net
        name: sops-key
        version: 24463ded09434256b46852a5cd1a6edf
        created_at: '2020-05-31T02:49:02Z'
        enc: oPl_BH8L_HuQGj3PgS6yJZ4MPV_qKDFTr-sNGooPcMLL8GvK05kaipDGTyH9NdLeOa6adTxydkRzZCVH1s434znWyAJUa70nTFkRm5K4Exy08peQFoAkTsPYG3aii7ByOieq7v5rB0oVxDZz6L5lbN6v9KnS3NPb-_ZusARb1mj4eEz1aGodgzTmrD2Bf7yK5zE_n2uPKDmISef_uVax_TfrkHpqPz8_wK2aMgBxUiBvZZiGDQLgJY_o7-B7koi1MK7jXoiCchIKXZxDF6ejEXkKY8iJXeFzZoUrlc9SkSLPHV56YamhMOl5bhv_CI5SGGthWDLKuC45VAD7Qqb3ug
    lastmodified: '2020-05-31T03:52:58Z'
    mac: ENC[AES256_GCM,data:bM8D+QEWMU5eZxynpvp+l8t7tCKf0OhoJfsoliQyvsP/MEqVQcj6KOhFfWPhzg0sK4Uox/1Fj4XjBHU2OH5v5vZ1R5ni0E8lmaBaByHmeuT7nWim/TLTZ1/YbFt0pRvZxme8BGoGJfEvsvBL/45neXVXnGsKs9uAaXBsz5c9b/s=,iv:IK2c7Bf/uUs77fK66oqD7UNbctMjONoqcTmKpQ83j3o=,tag:KuuA55jRj536XFngwdtWBA==,type:str]
    pgp:
    -   created_at: '2020-05-31T02:49:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9rJtJUODAqKAQgAmw4Zk7VilT5kdxD9n1QubDgp2YEyxSNblFhwrNu5aT1c
            WbGwocrREkLRYpw6FobSz7g7691Nk+60nihfON5nNB+AzJYtWaoATzpwretdKUBF
            y9Z7ku2ag/Jg8lYXFoYIwCvIac68UjZ8ABjiavH+Isl/uYFMj9nRLEw3kca5aeBa
            O8ya/hF6V1zYxP/anI6bgGQCjuZAH9FCHa7qbBxHIBRUUgUqGccdo7R2UdiczhY2
            pwOo/evSK8JE4Wq921DD+8nrp+YuU3ybJXgUHswULNtabZDkW2i71gKMu/jHfL8v
            24Y3/f1fcJkg3i7cxbf6mP+jS7OCAIx5qXGR3oKYONJeAcrtynkO4ASuFUr8+Hbe
            lQUWW/Hgu/H5D/C2ThZ477BJGkuGyUPIySAtR48Pklwem/hzfLQt5RBUvJ8mX3/i
            dZ1dbw7Oj7TeYKzeHXzp2louosANZWraFTYhGlWsMA==
            =llv+
            -----END PGP MESSAGE-----
        fp: 8CC3DBB98A442086023F9766A5296C151AD0CA9E
    -   created_at: '2020-05-31T02:49:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA79ZFHB1EZo1AQf/aZonHva/Z/UX4pB0oxd/ABoe+QYwyy0IBj2Mo3O8nVbs
            WyrihJJS9Lc/dXVmM0V3ifRzbSz1fqora7bpySRCGaoqLN8jG44hmZ21sHu4fi8W
            vZmE0d8qyX328RblCRsug0twQqTAaOCnHTSQ7wDhiDVCHIVjq3w6QjFsFuDr5Gx+
            Pj0HOa1NAT9u9oBvh34kQifV9KSTtwsyV+vSNaCDuQNBNuOkykXddkA3MMGcNIRk
            VKzQnoY2zRtQzOWIYVexOd74X3BY0FMU9a3mVpClwMWTHsxjIXUwH3LXdLuuAXmf
            DIbw64vNZ1KwE/aw8u2QqyPSKth9B6RQD16PGCKRtdJeAbsO3CirvbrNH2AVuA5r
            EwBLvztTMHkrhZINzYZCVFly/6cUk9RylkYyCOM3iUAMeLXXWrlVOEA/LNvW262x
            9C7qdoYcUGJX61yYqMAWatRh/wJX/gzLDPYze0Vw7w==
            =TWb7
            -----END PGP MESSAGE-----
        fp: 4C70A838416441A4E5A476B46E17861CCB27B2FB
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
