apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace will be defined by the caller using kustomize edit set namespace ${namespace}
namespace: argo

# bases:
#   - ../../../base/fluent-bit

resources:
  # - https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
  - ./install-2.5.yaml
  # - ./certificate-raseedy-stg.yaml
  # # - ./certificate-raseedy-prod.yaml

# generators:
# - ./secret-generator.yaml

